name: Release Creation

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Setting variables part 1
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build Main and Rest Modules
        env:
          APP_VERSION: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          bash ./build.sh

      - name: Create GitHub Release
        uses: actions/github-script@v3
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo }, sha } = context;

            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: process.env.SOURCE_TAG,
              draft: false,
              target_commitish: sha,
              name: 'AppUtils Tools ' + process.env.SOURCE_TAG
            });

            for (let file of await fs.readdir('./dist')) {
              console.log('Uploading -> ', file);

              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./dist/${file}`)
              });
            }
      - name: Publish Components to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          export COMMIT_ID="$(git log --format=%H -n 1)"
          export COMMIT_MSG="$(git log --format=%B -n 1)"
          echo "=================================="
          echo "Commit ID: ${COMMIT_ID}"
          echo "COMMIT_MSG: ${COMMIT_MSG}"
          echo "=================================="
          twine upload -r pypi -c "${COMMIT_MSG} (${COMMIT_ID})" --skip-existing ./dist/*